/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    banner: string;
    banner__container: string;
    banner__icon_text: string;
    banner__icon_wrapper: string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
