/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    banner: string;
    banner__btn: string;
    banner__container: string;
    banner__icon_text: string;
    banner__icon_wrapper: string;
    banner__list: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
