/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    banner: string;
    banner__container: string;
    banner__icon_btn: string;
    banner__icon_text: string;
    banner__icon_tooltip: string;
    banner__spacing: string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
