/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    drawer: string;
    drawer__btn_container: string;
    drawer__container: string;
    drawer__item: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
