/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    drawer: string;
    drawer__btn_container: string;
    drawer__container: string;
    drawer__item: string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
