/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'color-black': string;
    'color-primary': string;
    'color-secondary': string;
    'color-white': string;
    contact: string;
    contact__checkbox_container: string;
    contact__container: string;
    contact__form_container: string;
    contact__info: string;
    contact__photo: string;
    contact__submit_btn: string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
