/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    contact: string;
    contact__checkbox_container: string;
    contact__container: string;
    contact__form_container: string;
    contact__info: string;
    contact__photo: string;
    contact__submit_btn: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
