/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    gradient: string;
    hero: string;
    hero__btn: string;
    hero__heading: string;
    hero__info_container: string;
    hero__intro: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
