/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    img_container: string;
    img_container__frame: string;
    img_container__img: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
