/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    card: string;
    card__btn: string;
    card__details: string;
    card__logo: string;
    card__logos: string;
    card__more_details: string;
    'card__more_details--show': string;
    'card--expanded': string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
