/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    social_media_links: string;
    social_media_links__link: string;
    social_media_links__link_img: string;
    'social_media_links__link--black': string;
    'social_media_links__link--white': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
