/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'color-black': string;
    'color-primary': string;
    'color-secondary': string;
    'color-white': string;
    gradient: string;
    social_media_links: string;
    social_media_links__link: string;
    social_media_links__link_img: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
