/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    body: string;
    body__separator: string;
    body__text: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
