/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    about: string;
    about__container: string;
    about__text_container: string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
