/** @format */

const config = {
    banner: '// Auto generated by typed-scss-modules',
    exportType: 'default',
    nameFormat: 'none',
    includePaths: ['src/styles/sass'],
};

export default config;
