/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    bgImgDark: string;
    bgImgLight: string;
    colorPrimary: string;
    colorSecondary: string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
