/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    'breakpoint-lg-laptop': string;
    'breakpoint-md-tablet': string;
    'breakpoint-sm-tablet': string;
    'breakpoint-xl-desktop': string;
    'breakpoint-xs-mobile': string;
    'breakpoint-xxs-mobile': string;
    colorBgDefault: string;
    colorBgDefaultDark: string;
    colorPrimaryOriginal: string;
    colorSecondaryOriginal: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
