/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    'anim-wave': string;
    colorBgDefault: string;
    colorBgDefaultDark: string;
    colorPrimaryOriginal: string;
    colorSecondaryOriginal: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
