/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    __next: string;
    _hj_feedback_container: string;
    'anim-gradient': string;
    dark: string;
    'grecaptcha-badge': string;
    light: string;
    'theme-bg': string;
    'user-dark': string;
    'user-light': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
