/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    banner: string;
    'banner--bg-only': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
