/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    btn: string;
    btn__wrapper: string;
    'btn--alert': string;
    'btn--default': string;
    'btn--gradient': string;
    'btn--neutral': string;
    'btn--outlined': string;
    'btn--text': string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
