/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    'anim-wave': string;
    btn: string;
    'btn--default': string;
    'btn--outlined': string;
    'btn--text': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
