/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    card: string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
