/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    'anim-wave': string;
    color_picker: string;
    color_picker__error: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
