/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'color-black': string;
    'color-primary': string;
    'color-secondary': string;
    'color-white': string;
    gradient: string;
    toggle: string;
    toggle__btn: string;
    'toggle__btn--disabled': string;
    'toggle__btn--enabled': string;
    'toggle--ready': string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
