/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    btn: string;
    btn__wrapper: string;
    'btn--disabled': string;
    'btn--enabled': string;
    'color-black': string;
    'color-primary': string;
    'color-secondary': string;
    'color-white': string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
