/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    heading: string;
    'heading--disable-pt': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
