/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    toggle: string;
    toggle__btn: string;
    'toggle__btn--disabled': string;
    'toggle__btn--enabled': string;
    'toggle--theme-resolved': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
