/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'color-black': string;
    'color-primary': string;
    'color-secondary': string;
    'color-white': string;
    gradient: string;
    wave: string;
    wrapper: string;
    wrapper__icon: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
