/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    wrapper: string;
    wrapper__icon: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
