/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    about: string;
    about__heading: string;
    about__text_container: string;
    'anim-gradient': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
