/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'color-black': string;
    'color-primary': string;
    'color-secondary': string;
    'color-white': string;
    gradient: string;
    overview: string;
    overview__chips: string;
    overview__container: string;
    overview__skills: string;
    overview__skills_hard: string;
    overview__skills_soft: string;
    overview__timeline: string;
    overview__timeline_content: string;
    'overview__timeline_content--mech': string;
    overview__timeline_paragraph: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
