/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    footer: string;
    footer__bottom: string;
    footer__built_using: string;
    footer__container: string;
    footer__copyright: string;
    footer__logos: string;
    footer__my_logo: string;
    footer__top: string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
