/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    footer: string;
    footer__bottom: string;
    footer__bottom_container: string;
    'footer__bottom_container--copyright': string;
    footer__bottom_links: string;
    footer__bottom_logo: string;
    footer__bottom_logos: string;
    footer__middle: string;
    footer__middle_btn: string;
    footer__middle_container: string;
    footer__top: string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
