/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    'anim-gradient': string;
    header: string;
    header__btns: string;
    header__content: string;
    header__content_bg: string;
    header__drawer: string;
    header__links: string;
    header__logo: string;
    header__menu: string;
    header__toolbar: string;
    'header--absolute': string;
    'header--fixed': string;
    'header--scrolled': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
