/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    gradient: string;
    header: string;
    header__btns: string;
    header__content: string;
    header__content_bg: string;
    header__links: string;
    header__logo: string;
    header__toolbar: string;
    'header--absolute': string;
    'header--fixed': string;
    'header--scrolled': string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
