/** @format */

// Auto generated by typed-scss-modules
export type Styles = {
    game_screen: string;
    game_screen__cards: string;
    'game_screen__cards--flipped': string;
    gradient: string;
    wave: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
